apiVersion: v1
kind: Service
metadata:
  name: chat-api-dev
  namespace: chat-api-dev
spec:
  selector:
    app: chat-api-dev
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
