apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-api-wiki
  namespace: chat-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-api-db
  namespace: chat-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
